import de.cispa.se.tribble.dsl._

// Translated from https://www.w3.org/Addressing/URL/5_BNF.html

Grammar(
//  'prefixedurl := "url:" ~ 'url,
  'url := 'httpaddress | 'ftpaddress | 'newsaddress | 'nntpaddress | 'prosperoaddress | 'telnetaddress | 'gopheraddress | 'waisaddress | 'mailtoaddress /*| 'midaddress | 'cidaddress*/,
//  'scheme := 'ialpha,
  'httpaddress := "http://" ~ 'hostport ~ ("/" ~ 'path).? ~ ("?" ~ 'search).?,
  'ftpaddress := "ftp://" ~ 'login ~ "/" ~ 'path ~ (";" ~ 'ftptype).?,
//  'afsaddress := "afs://" ~ 'cellname ~ "/" ~ 'path,
  'newsaddress := "news:" ~ 'groupart,
  'nntpaddress := "nntp:" ~ 'group ~ "/" ~ 'digits,
//  'midaddress := "mid:" ~ 'addrspec,
//  'cidaddress := "cid:" ~ 'contentidentifier,
  'mailtoaddress := "mailto:" ~ 'xalphas ~ "@" ~ 'hostname,
  'waisaddress := 'waisindex | 'waisdoc,
  'waisindex := "wais://" ~ 'hostport ~ "/" ~ 'database ~ ("?" ~ 'search).?,
  'waisdoc := "wais://" ~ 'hostport ~ "/" ~ 'database ~ "/" ~ 'wtype ~ "/" ~ 'wpath,
  'wpath := 'digits ~ "=" ~ 'path ~ ";" ~ 'wpath.?,
  'groupart := "*" | 'group | 'article,
  'group := 'ialpha ~ ("." ~ 'group).?,
  'article := 'xalphas ~ "@" ~ 'host,
  'database := 'xalphas,
  'wtype := 'xalphas,
  'prosperoaddress := 'prosperolink,
  'prosperolink := "prospero://" ~ 'hostport ~ "/" ~ 'hsoname ~ ("%00" ~ 'version ~ 'attributes.?).?,
  'hsoname := 'path,
  'version := 'digits,
  'attributes := 'attribute ~ 'attributes.?,
  'attribute := 'alphanums,
  'telnetaddress := "telnet://" ~ 'login,
  'gopheraddress := "gopher://" ~ 'hostport ~ ("/" ~ 'gtype ~ 'gcommand.?).?,
  'login := ('user ~ (":" ~ 'password).? ~ "@").? ~ 'hostport,
  'hostport := 'host ~ (":" ~ 'port).?,
  'host := 'hostname | 'hostnumber,
  'ftptype := "A" ~ 'formcode | "E" ~ 'formcode | "I" | "L" ~ 'digits,
  'formcode := "N" | "T" | "C",
//  'cellname := 'hostname,
  'hostname := 'ialpha ~ ("." ~ 'hostname).?,
  'hostnumber := 'digits ~ "." ~ 'digits ~ "." ~ 'digits ~ "." ~ 'digits,
  'port := 'digits,
  'gcommand := 'path,
  'path := "" | 'segment ~ ("/" ~ 'path).?,
  'segment := 'xpalphas,
  'search := 'xalphas ~ ("+" ~ 'search).?,
  'user := 'alphanum2 ~ 'user.?,
  'password := 'alphanum2 ~ 'password.?,
//  'fragmentid := 'xalphas,
  'gtype := 'xalpha,
  'alphanum2 := 'alpha | 'digit | "-" | "_" | "." | "+",
  'xalpha := 'alpha | 'digit | 'safe | 'extra | 'escape,
  'xalphas := 'xalpha ~ 'xalphas.?,
  'xpalpha := 'xalpha | "+",
  'xpalphas := 'xpalpha ~ 'xpalphas.?,
  'ialpha := 'alpha ~ 'xalphas.?,
  'alpha := "[a-zA-Z]".regex,
  'digit := "[0-9]".regex,
  'safe := "$" | "_" | "@" | "." | "&" | "+" | "-",
  'extra := "!" | "*" | "\"" | "'" | "(" | ")" | ",",
//  'reserved := "=" | ";" | "/" | "#" | "?" | ":" | " ",
  'escape := "%" ~ 'hex ~ 'hex,
  'hex := "[0-9a-fA-F]".regex,
//  'national := "{" | "}" | "|" | "[" | "]" | "\\" | "^" | "~",
//  'punctuation := "<" | ">",
  'digits := 'digit ~ 'digits.?,
  'alphanum := 'alpha | 'digit,
  'alphanums := 'alphanum ~ 'alphanums.?
)
